import { type Topic, type MediaItem, type CalendarEvent, type Grade, type Profile, type Plancha, type MockUser } from '@/types';

export const GRADES: Grade[] = [
    { id: 'grade-1', name: 'Aprendiz', slug: 'aprendiz', order: 1 },
    { id: 'grade-2', name: 'Compañero', slug: 'companero', order: 2 },
    { id: 'grade-3', name: 'Maestro', slug: 'maestro', order: 3 },
];

export const MOCK_PROFILES: Record<string, Profile> = {
    'user-student': {
        id: 'user-student',
        full_name: 'Hermano Demo',
        grade_id: 'grade-2',
        role: 'student',
        grade: GRADES[1],
    },
    'user-admin': {
        id: 'user-admin',
        full_name: 'Administrador',
        grade_id: 'grade-2',
        role: 'admin',
        grade: GRADES[1],
    },
};

export const MOCK_USERS: MockUser[] = [
    {
        id: 'u-admin-test',
        full_name: 'Vigilante Test',
        email: 'admin@test.com',
        password: 'caelum671',
        role: 'admin',
        grade_id: 'grade-3',
        grade_slug: 'maestro',
    },
    // Vigilantes (admin)
    {
        id: 'u-1',
        full_name: 'H.·. Roberto Silva',
        email: 'admin@demo.com',
        password: 'demo1234',
        role: 'admin',
        grade_id: 'grade-3',
        grade_slug: 'maestro',
    },
    {
        id: 'u-2',
        full_name: 'H.·. Luis Medina',
        email: 'vigilante2@demo.com',
        password: 'demo1234',
        role: 'admin',
        grade_id: 'grade-2',
        grade_slug: 'companero',
    },
    // Estudiantes – Aprendices
    {
        id: 'u-3',
        full_name: 'H.·. Carlos Pérez',
        email: 'aprendiz1@demo.com',
        password: 'demo1234',
        role: 'student',
        grade_id: 'grade-1',
        grade_slug: 'aprendiz',
    },
    {
        id: 'u-4',
        full_name: 'H.·. Martín López',
        email: 'aprendiz2@demo.com',
        password: 'demo1234',
        role: 'student',
        grade_id: 'grade-1',
        grade_slug: 'aprendiz',
    },
    // Estudiantes – Compañeros
    {
        id: 'u-5',
        full_name: 'H.·. Diego Ramos',
        email: 'companero@demo.com',
        password: 'demo1234',
        role: 'student',
        grade_id: 'grade-2',
        grade_slug: 'companero',
    },
    // Estudiantes – Maestros
    {
        id: 'u-6',
        full_name: 'H.·. Eduardo Torres',
        email: 'maestro@demo.com',
        password: 'demo1234',
        role: 'student',
        grade_id: 'grade-3',
        grade_slug: 'maestro',
    },
];



export const MOCK_TOPICS: Topic[] = [
    // ── Aprendiz (grade-1) ──────────────────────────────────────────
    {
        id: 'topic-a1',
        grade_id: 'grade-1',
        title: 'Entrada al Templo: El Primer Paso',
        description: 'Significado del umbral, la oscuridad y la luz en la iniciación del Aprendiz.',
        order: 1,
        resources: [
            { id: 'res-a1', topic_id: 'topic-a1', title: 'Ritual de Iniciación – 1.er Grado', description: null, type: 'pdf', url: 'https://drive.google.com/file/d/APRENDIZ1', order: 1 },
        ],
    },
    {
        id: 'topic-a2',
        grade_id: 'grade-1',
        title: 'Las Herramientas del Aprendiz',
        description: 'Estudio simbólico de la regla de 24 pulgadas, el mazo y el cincel como instrumentos de trabajo moral.',
        order: 2,
        resources: [
            { id: 'res-a2', topic_id: 'topic-a2', title: 'Plancha: Las Herramientas', description: null, type: 'pdf', url: 'https://drive.google.com/file/d/APRENDIZ2', order: 1 },
        ],
    },
    {
        id: 'topic-a3',
        grade_id: 'grade-1',
        title: 'Los Tres Pilares y las Tres Luces',
        description: 'Sabiduría, Fuerza y Belleza como columnas fundamentales de la Logia y del carácter masónico.',
        order: 3,
        resources: [],
    },
    {
        id: 'topic-a4',
        grade_id: 'grade-1',
        title: 'La Piedra Bruta',
        description: 'Reflexión sobre el estado natural del hombre y el trabajo necesario para desbastarlo y perfeccionarlo.',
        order: 4,
        resources: [],
    },
    // ── Maestro (grade-3) ───────────────────────────────────────────
    {
        id: 'topic-m1',
        grade_id: 'grade-3',
        title: 'El Maestro y la Palabra Perdida',
        description: 'Profundización en el drama del Tercer Grado: la muerte simbólica, la búsqueda y la resurrección.',
        order: 1,
        resources: [
            { id: 'res-m1', topic_id: 'topic-m1', title: 'Ritual del Tercer Grado', description: null, type: 'pdf', url: 'https://drive.google.com/file/d/MAESTRO1', order: 1 },
        ],
    },
    {
        id: 'topic-m2',
        grade_id: 'grade-3',
        title: 'La Cámara del Medio',
        description: 'El acceso al sancta sanctórum: condiciones, simbolismo y responsabilidad del Maestro Masón.',
        order: 2,
        resources: [],
    },
    // ── Compañero (grade-2) ─────────────────────────────────────────
    {
        id: 'topic-1',

        grade_id: 'grade-2',
        title: 'Iniciación al Grado Compañero',
        description: 'Introducción a los rituales, herramientas y símbolos del segundo grado masónico.',
        order: 1,
        resources: [
            {
                id: 'res-1',
                topic_id: 'topic-1',
                title: 'Ritual de Iniciación (PDF)',
                description: 'Documento completo del ritual de paso al segundo grado.',
                type: 'pdf',
                url: 'https://drive.google.com/file/d/EJEMPLO1',
                order: 1,
            },
            {
                id: 'res-2',
                topic_id: 'topic-1',
                title: 'Video: Introducción al Grado',
                description: 'Explicación audiovisual de los conceptos fundamentales del Compañero.',
                type: 'video',
                url: 'https://drive.google.com/file/d/EJEMPLO2',
                order: 2,
            },
            {
                id: 'res-3',
                topic_id: 'topic-1',
                title: 'Lecturas complementarias',
                description: 'Selección de textos recomendados para profundizar el estudio.',
                type: 'link',
                url: 'https://ejemplo.com/lecturas',
                order: 3,
            },
        ],
    },
    {
        id: 'topic-2',
        grade_id: 'grade-2',
        title: 'Las Cinco Órdenes de Arquitectura',
        description: 'Estudio de los órdenes arquitectónicos clásicos y su profundo significado simbólico.',
        order: 2,
        resources: [
            {
                id: 'res-4',
                topic_id: 'topic-2',
                title: 'Presentación: Órdenes Arquitectónicas',
                description: 'Slides con imágenes de los cinco órdenes arquitectónicos clásicos.',
                type: 'drive',
                url: 'https://drive.google.com/presentation/d/EJEMPLO3',
                order: 1,
            },
            {
                id: 'res-5',
                topic_id: 'topic-2',
                title: 'Audio: Meditación sobre los Pilares',
                description: 'Meditación guiada de 20 minutos sobre el simbolismo de los pilares.',
                type: 'audio',
                url: 'https://drive.google.com/file/d/EJEMPLO4',
                order: 2,
            },
            {
                id: 'res-6',
                topic_id: 'topic-2',
                title: 'Manual de Estudio – Tomo II',
                description: 'Texto de referencia para el estudio de las proporciones áureas.',
                type: 'pdf',
                url: 'https://drive.google.com/file/d/EJEMPLO5',
                order: 3,
            },
        ],
    },
    {
        id: 'topic-3',
        grade_id: 'grade-2',
        title: 'La Escalera de Caracol',
        description: 'El ascenso al conocimiento: las siete ciencias liberales y las artes mecánicas.',
        order: 3,
        resources: [
            {
                id: 'res-7',
                topic_id: 'topic-3',
                title: 'Las Siete Artes Liberales (PDF)',
                description: 'Gramática, Retórica, Lógica, Aritmética, Geometría, Música y Astronomía.',
                type: 'pdf',
                url: 'https://drive.google.com/file/d/EJEMPLO6',
                order: 1,
            },
            {
                id: 'res-8',
                topic_id: 'topic-3',
                title: 'Conferencia: El Trivium y el Quadrivium',
                description: 'Conferencia completa sobre el sistema educativo clásico.',
                type: 'video',
                url: 'https://ejemplo.com/conferencia',
                order: 2,
            },
        ],
    },
    {
        id: 'topic-4',
        grade_id: 'grade-2',
        title: 'Signos y Palabras del Grado',
        description: 'Estudio esotérico de los signos de reconocimiento del segundo grado.',
        order: 4,
        resources: [
            {
                id: 'res-9',
                topic_id: 'topic-4',
                title: 'Guía de Signos Rituales',
                description: 'Guía práctica ilustrada con el significado de cada signo.',
                type: 'drive',
                url: 'https://drive.google.com/file/d/EJEMPLO7',
                order: 1,
            },
        ],
    },
    {
        id: 'topic-5',
        grade_id: 'grade-2',
        title: 'La Estrella de Cinco Puntas',
        description: 'La Estrella Flamígera: geometría sagrada y simbolismo del pentagrama masónico.',
        order: 5,
        resources: [
            {
                id: 'res-10',
                topic_id: 'topic-5',
                title: 'Documento: Geometría Sagrada',
                description: 'Análisis detallado de la proporción áurea y la estrella flamígera.',
                type: 'pdf',
                url: 'https://drive.google.com/file/d/EJEMPLO8',
                order: 1,
            },
            {
                id: 'res-11',
                topic_id: 'topic-5',
                title: 'Recursos Externos – Geometría',
                description: 'Colección de sitios y artículos de referencia sobre geometría masónica.',
                type: 'link',
                url: 'https://ejemplo.com/geometria',
                order: 2,
            },
        ],
    },
];

export const MOCK_MEDIA: MediaItem[] = [
    // ── Aprendiz (grade-1) ──────────────────────────────────────────
    {
        id: 'media-a1',
        grade_id: 'grade-1',
        title: 'Documental: El Camino del Aprendiz',
        description: 'Introducción audiovisual al primer grado: simbolismo, herramientas y pruebas de la iniciación.',
        type: 'video',
        url: 'https://ejemplo.com/aprendiz-documental',
    },
    {
        id: 'media-a2',
        grade_id: 'grade-1',
        title: 'Podcast: La Piedra Bruta y el Trabajo Interior',
        description: 'Reflexión sobre la transformación personal como piedra fundamental del trabajo masónico.',
        type: 'audio',
        url: 'https://ejemplo.com/podcast-aprendiz',
    },
    {
        id: 'media-a3',
        grade_id: 'grade-1',
        title: 'Manual del Aprendiz (PDF)',
        description: 'Guía de estudio oficial para el primer grado. Rituales, símbolos y obligaciones.',
        type: 'pdf',
        url: 'https://drive.google.com/file/d/MANUAL_A',
    },
    {
        id: 'media-a4',
        grade_id: 'grade-1',
        title: 'Lecturas Recomendadas – Aprendiz',
        description: 'Selección de textos y recursos web para el estudio del primer grado.',
        type: 'link',
        url: 'https://ejemplo.com/lecturas-aprendiz',
    },
    // ── Compañero (grade-2) ─────────────────────────────────────────
    {
        id: 'media-1',
        grade_id: 'grade-2',
        title: 'Documental: Historia de la Masonería',
        description: 'Serie documental completa en tres partes sobre el origen e historia de la Orden.',
        type: 'video',
        url: 'https://ejemplo.com/documental',
    },
    {
        id: 'media-2',
        grade_id: 'grade-2',
        title: 'Conferencia: Los Misterios del Compañero',
        description: 'Conferencia magistral de 90 minutos por el V.·. H.·. Maestro de Ceremonias.',
        type: 'video',
        url: 'https://ejemplo.com/conferencia-misterios',
    },
    {
        id: 'media-3',
        grade_id: 'grade-2',
        title: 'Podcast: Viaje al Segundo Grado',
        description: 'Episodio 1 de la serie de podcasts. Reflexiones sobre el paso de Aprendiz a Compañero.',
        type: 'audio',
        url: 'https://ejemplo.com/podcast-ep1',
    },
    {
        id: 'media-4',
        grade_id: 'grade-2',
        title: 'Podcast: Los Pilares – Boaz y Jaquin',
        description: 'Análisis profundo del simbolismo de los dos grandes pilares del Templo de Salomón.',
        type: 'audio',
        url: 'https://ejemplo.com/podcast-ep2',
    },
    {
        id: 'media-5',
        grade_id: 'grade-2',
        title: 'Manual del Compañero (PDF)',
        description: 'Guía de estudio oficial para el segundo grado. Versión revisada 2025.',
        type: 'pdf',
        url: 'https://drive.google.com/file/d/MANUAL',
    },
    {
        id: 'media-6',
        grade_id: 'grade-2',
        title: 'Trazado de la Tabla del Compañero',
        description: 'Documento completo con el trazado de la plancha del segundo grado.',
        type: 'pdf',
        url: 'https://drive.google.com/file/d/TRAZADO',
    },
    {
        id: 'media-7',
        grade_id: 'grade-2',
        title: 'Recursos Online Recomendados',
        description: 'Colección curada de links externos: bibliotecas, instituciones y artículos verificados.',
        type: 'link',
        url: 'https://ejemplo.com/recursos-online',
    },
    {
        id: 'media-8',
        grade_id: 'grade-2',
        title: 'Biblioteca Digital Masónica',
        description: 'Acceso al portal de la Gran Logia con materiales para el segundo grado.',
        type: 'link',
        url: 'https://ejemplo.com/biblioteca-digital',
    },
    // ── Maestro (grade-3) ───────────────────────────────────────────
    {
        id: 'media-m1',
        grade_id: 'grade-3',
        title: 'Conferencia: La Palabra Perdida y el Misterio del Tercer Grado',
        description: 'Análisis filosófico del drama del Maestro Masón y su resurrección simbólica.',
        type: 'video',
        url: 'https://ejemplo.com/maestro-conferencia',
    },
    {
        id: 'media-m2',
        grade_id: 'grade-3',
        title: 'Manual del Maestro Masón (PDF)',
        description: 'Guía completa del tercer grado: ritual, simbolismo y responsabilidades del Maestro.',
        type: 'pdf',
        url: 'https://drive.google.com/file/d/MANUAL_M',
    },
    {
        id: 'media-m3',
        grade_id: 'grade-3',
        title: 'Podcast: La Cámara del Medio y sus Secretos',
        description: 'Reflexión sobre los misterios reservados al Maestro y la responsabilidad de su custodia.',
        type: 'audio',
        url: 'https://ejemplo.com/podcast-maestro',
    },
];



export const MOCK_EVENTS: CalendarEvent[] = [
    {
        id: 'event-1',
        grade_id: 'grade-2',
        title: 'Tenida Regular – Marzo',
        description: 'Tenida mensual del Grado Compañero. Asistencia obligatoria con traje de rigor.',
        event_date: '2026-03-14',
        event_type: 'ritual',
    },
    {
        id: 'event-2',
        grade_id: 'grade-2',
        title: 'Taller: Simbolismo Arquitectónico',
        description: 'Taller práctico sobre los cinco órdenes y su aplicación simbólica.',
        event_date: '2026-03-21',
        event_type: 'taller',
    },
    {
        id: 'event-3',
        grade_id: 'grade-2',
        title: 'Tenida Regular – Abril',
        description: 'Tenida mensual del Grado Compañero.',
        event_date: '2026-04-11',
        event_type: 'ritual',
    },
    {
        id: 'event-4',
        grade_id: 'grade-2',
        title: 'Conferencia: Las Siete Artes Liberales',
        description: 'Conferencia abierta para todos los grados sobre el Trivium y el Quadrivium.',
        event_date: '2026-04-25',
        event_type: 'taller',
    },
    {
        id: 'event-5',
        grade_id: 'grade-2',
        title: 'Tenida Regular – Mayo',
        description: 'Tenida mensual del Grado Compañero con trazado de plancha.',
        event_date: '2026-05-09',
        event_type: 'ritual',
    },
    {
        id: 'event-6',
        grade_id: 'grade-2',
        title: 'Examen de Avance',
        description: 'Evaluación formal para la progresión al tercer grado. Preparación requerida.',
        event_date: '2026-06-06',
        event_type: 'examen',
    },
    {
        id: 'event-7',
        grade_id: 'grade-2',
        title: 'Tenida Regular – Junio',
        description: 'Tenida mensual. Resultados y comunicaciones del Venerable Maestro.',
        event_date: '2026-06-20',
        event_type: 'ritual',
    },
    {
        id: 'event-8',
        grade_id: 'grade-2',
        title: 'Tenida Solemne – Julio',
        description: 'Tenida especial con la presencia de representantes de la Gran Logia.',
        event_date: '2026-07-18',
        event_type: 'general',
    },
];

export const MOCK_PLANCHAS: Plancha[] = [
    // ── Aprendiz (grade-1) ──────────────────────────────────────────
    {
        id: 'plancha-a1',
        grade_id: 'grade-1',
        topic_id: 'topic-a1',
        title: 'El Umbral: Reflexión sobre la Iniciación',
        author: 'H.·. Pablo N.',
        date: '2025',
        description: 'Plancha de reflexión personal sobre el primer paso en la Orden: la oscuridad, la prueba y la luz al final del camino iniciático.',
        tags: ['iniciación', 'reflexión', 'aprendiz'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA_A1',
        order_index: 1,
        created_at: '2025-06-01T10:00:00Z',
    },
    {
        id: 'plancha-a2',
        grade_id: 'grade-1',
        topic_id: 'topic-a2',
        title: 'La Regla de 24 Pulgadas y el Tiempo del Aprendiz',
        author: 'H.·. Matías C.',
        date: '2025',
        description: 'Estudio simbólico de la regla de 24 pulgadas como herramienta para la gestión del tiempo y el equilibrio entre el trabajo, la oración y el reposo.',
        tags: ['herramientas', 'aprendiz', 'simbolismo'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA_A2',
        order_index: 2,
        created_at: '2025-08-15T10:00:00Z',
    },
    // ── Compañero (grade-2) ─────────────────────────────────────────
    {
        id: 'plancha-1',
        grade_id: 'grade-2',
        topic_id: 'topic-1',
        title: 'Reflexión sobre el Paso de Aprendiz a Compañero',
        author: 'H.·. Juan M.',
        date: '2024',
        description: 'Reflexión personal sobre el significado del cambio de grado, los compromisos adquiridos y el nuevo camino de aprendizaje que se abre.',
        tags: ['ritual', 'iniciación', 'reflexión'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA1',
        order_index: 3,
        created_at: '2024-03-15T10:00:00Z',
    },
    {
        id: 'plancha-2',
        grade_id: 'grade-2',
        topic_id: 'topic-2',
        title: 'El Orden Dórico y su Simbolismo',
        author: 'H.·. Carlos R.',
        date: '2024',
        description: 'Análisis detallado del orden dórico, su simplicidad, proporciones y representación de la fortaleza moral en la construcción del templo interior.',
        tags: ['arquitectura', 'simbolismo', 'órdenes'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA2',
        order_index: 4,
        created_at: '2024-05-22T10:00:00Z',
    },
    {
        id: 'plancha-3',
        grade_id: 'grade-2',
        topic_id: 'topic-3',
        title: 'La Gramática como Base del Conocimiento',
        author: 'H.·. Miguel A.',
        date: '2025',
        description: 'Plancha sobre la gramática como primera de las artes liberales y su rol en la construcción del pensamiento masónico y la comunicación fraternal.',
        tags: ['artes liberales', 'gramática', 'conocimiento'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA3',
        order_index: 5,
        created_at: '2025-01-10T10:00:00Z',
    },
    {
        id: 'plancha-4',
        grade_id: 'grade-2',
        topic_id: 'topic-5',
        title: 'La Estrella Flamígera y el Número Cinco',
        author: 'H.·. Roberto L.',
        date: '2025',
        description: 'Estudio sobre el pentagrama masónico, su relación con la proporción áurea, los cinco sentidos y su manifestación en la naturaleza y la geometría sagrada.',
        tags: ['geometría', 'estrella', 'simbolismo'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA4',
        order_index: 6,
        created_at: '2025-03-08T10:00:00Z',
    },
    {
        id: 'plancha-5',
        grade_id: 'grade-2',
        title: 'Los Dos Pilares: Boaz y Jaquin',
        author: 'H.·. Diego F.',
        date: '2025',
        description: 'Investigación sobre el origen histórico y el significado esotérico de los dos pilares de bronce del Templo de Salomón y su proyección en la vida del Compañero.',
        tags: ['pilares', 'templo', 'historia'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA5',
        order_index: 7,
        created_at: '2025-04-20T10:00:00Z',
    },
    {
        id: 'plancha-6',
        grade_id: 'grade-2',
        topic_id: 'topic-4',
        title: 'Los Signos y la Palabra Sagrada del Segundo Grado',
        author: 'H.·. Andrés G.',
        date: '2026',
        description: 'Plancha filosófica sobre el significado de los signos de reconocimiento y su función como vínculo fraternal entre compañeros de grado a través del tiempo y el espacio.',
        tags: ['signos', 'reconocimiento', 'fraternidad'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA6',
        order_index: 8,
        created_at: '2026-01-12T10:00:00Z',
    },
    {
        id: 'plancha-7',
        grade_id: 'grade-2',
        title: 'La Geometría: Madre de las Artes',
        author: 'H.·. Eduardo S.',
        date: '2026',
        description: 'Exploración de la geometría como fundamento de toda arquitectura, arte y ciencia, y su rol central en el simbolismo masónico desde los orígenes operativos de la Orden.',
        tags: ['geometría', 'artes liberales', 'arquitectura'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA7',
        order_index: 9,
        created_at: '2026-02-05T10:00:00Z',
    },
    {
        id: 'plancha-8',
        grade_id: 'grade-2',
        title: 'El Trabajo en la Piedra Bruta y la Piedra Cúbica',
        author: 'H.·. Fernando P.',
        date: '2026',
        description: 'Reflexión sobre el trabajo interior del masón: la transformación de la piedra bruta en piedra cúbica como alegoría del perfeccionamiento moral y espiritual del Compañero.',
        tags: ['piedra', 'trabajo interior', 'perfeccionamiento'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA8',
        order_index: 10,
        created_at: '2026-03-01T10:00:00Z',
    },
    // ── Maestro (grade-3) ───────────────────────────────────────────
    {
        id: 'plancha-m1',
        grade_id: 'grade-3',
        topic_id: 'topic-m1',
        title: 'Hiram Abiff y el Misterio de la Muerte Simbólica',
        author: 'H.·. Roberto Silva',
        date: '2025',
        description: 'Profundo análisis del drama de Hiram Abiff como arquetipo de la muerte iniciática y la búsqueda de la resurrección espiritual en la tradición masónica occidental.',
        tags: ['maestro', 'misterio', 'simbolismo'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA_M1',
        order_index: 11,
        created_at: '2025-09-10T10:00:00Z',
    },
    {
        id: 'plancha-m2',
        grade_id: 'grade-3',
        topic_id: 'topic-m2',
        title: 'La Palabra Perdida y la Tradición Esotérica',
        author: 'H.·. Eduardo Torres',
        date: '2026',
        description: 'Investigación comparada sobre la búsqueda de la Palabra Perdida en diversas tradiciones iniciáticas y su correlato en el camino del Maestro Masón.',
        tags: ['maestro', 'palabra', 'esoterismo'],
        resource_url: 'https://drive.google.com/file/d/PLANCHA_M2',
        order_index: 12,
        created_at: '2026-02-20T10:00:00Z',
    },
];

